# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2024 Harshil Dave <harshil128@gmail.com>

# List of cities for training
cities:
  - "Piedmont, California, USA"
  - "Oakland, California, USA"
  - "Berkeley, California, USA"
  - "San Francisco, California, USA"

# Maximum number of taxis in the environment
max_taxis: 10

# Maximum number of passengers in the environment
max_passengers: 20

# Probability of spawning a new passenger at each time step
passenger_spawn_probability: 0.1

# Training parameters
num_episodes: 1000
batch_size: 64
replay_buffer_capacity: 10000

# Hyperparameters for the DdpgAgent
actor_learning_rate: 0.0001
critic_learning_rate: 0.001
gamma: 0.99
tau: 0.005

# Exploration parameters
exploration_noise_std: 0.1
exploration_noise_clip: 0.5

# Network architecture
actor_hidden_layers:
  - 128
  - 64
critic_hidden_layers:
  - 128
  - 64

# Training frequency
train_every_n_steps: 1
train_iterations: 1

# Logging and checkpointing
log_every_n_episodes: 10
checkpoint_every_n_episodes: 100

# Evaluation
eval_num_episodes: 5
